version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.12
  build:
    commands:
      - ls -lah
      - GO111MODULE=on go build
      - ls -lah
artifacts:
  files:
    - "**/*"
  name: $(date +%Y%m%d%M%S)_$CODEBUILD_SOURCE_VERSION
