version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.12
  build:
    commands:
      - ls -lah
      - go build main.go
      - ls -lah
artifacts:
  files:
    - "**/*"
  name: $(date +%Y-%m-%d)
